### ISSUE TITLE
Error loading Wisej-3 library (3. * - *)

### ISSUE THREAD

**Issue by heracomp** [iceteagroup/Wisej-3-Beta#14]
When generating a project with Wisej 3, it does not allow me to compile the project and it gives me the following error when trying to update the Wisej-3 (3. * - *) library with NuGet:
Failed to retrieve information about 'Wisej-3' from remote source 'https: // packagesource / FindPackagesById ()? Id =' Wisej-3 '& semVerLevel = 2.0.0'.
   An error occurred while sending the request.
   The remote name could not be resolved: 'packagesource'

**Comment by heracomp** [comment]
![Error_Wisej_3](https://user-images.githubusercontent.com/44346105/146973734-d075a447-c9fb-4133-9bfd-9cb91bfdb817.png)

**Comment by FrankITG** [comment]
Hi,
did you follow the steps in the "Get Started" Chapter?
https://docs.wisej.com/wisej-3-beta/getting-started/getting-started
Especially the part regarding the Package Sources?

Best regards
Frank

**Comment by heracomp** [comment]
I already solved the problem and what I did was delete the Wisej-3 (3 * - *) library and then update it with the new Wisej-3 version (3.0.1-beta.7) with the NuGet administrator.
Thanks Frank
Greetings

**Comment by AlaaTrAce** [comment]
Hi @heracomp,

Hopefully is going smoothly right now!

I just wanted to point something out regarding this issue.
![Capture](https://user-images.githubusercontent.com/57464198/147162235-cac68a9a-d73c-4b2d-813e-9653ea95812a.PNG)

The error you got is from an error in one of the NuGet package sources.
https://packagesource is the default source when adding a new Package Source from VS.

With that, sometimes when you wish to install or re-install a NuGet package it might error out since the Package Manager indexes all of the sources available.

HTH,
Alaa
